### ISSUE TITLE
[Bug🐛] Tailwind "flex" 중첩사용

### ISSUE THREAD

**Issue by mgm11063** [touch-flow-team/touch-flow#22]
> ## 설명
> 간단한 오류 / Tailwind flex 중첩사용

----

> ## 버그 주소 OR 버그 디렉토리

```
📇 URL : `frontend/components/companies/WaitConfirmModal.tsx`
```
----

> ## 상세설명
> flex가 두번 사용되고있어서 경고성 에러가 발생했습니다!

----

**Comment by soomin9106** [comment]
feature/12-waiting branch 에 fix commit 올렸습니다!!
